language: elixir
elixir:
  - 1.5.1
  - 1.4.4
otp_release:
  - 20.0
  - 19.2
services:
  - postgresql
before_script:
  - psql -c 'create database gatekeeper_test;' -U postgres
  - mix local.rebar --force # for Elixir 1.3.0 and up
  - mix local.hex --force
  - mix deps.get
  - mix deps.compile
  - mix deps.compile # second build for bug in `serial`
  - mix ecto.migrate
script: mix test
env:
  - SECRET_KEY_BASE=AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA MIX_ENV=test
matrix:
  allow_failures:
    # This particular combination results in a 403 while fetching the Elixir package from hex.pm
    - otp_release: 20.0
      elixir: 1.4.4
