---
# This assumes that the door is running a Raspberry Pi.
- hosts: all
  remote_user: pi
  sudo: yes
  tasks:
  - stat: path=/usr/bin/raspi-config
    register: raspi_config
  - stat: path=/etc/rootfs-expanded
    register: check_rootfs_expanded
  - name: "Expand root filesystem on Raspberry Pi"
    shell: /usr/bin/raspi-config --expand-rootfs
    when: raspi_config.stat.xusr is defined and raspi_config.stat.xusr and not check_rootfs_expanded.stat.exists
  - file: path=/etc/rootfs-expanded state=touch
    when: check_rootfs_expanded.stat.exists is not defined
  - name: reboot to get larger rootfs
    command: shutdown -r now "Ansible triggered - grow root filesystem"
    async: 0
    poll: 0
    ignore_errors: true
    when: not check_rootfs_expanded.stat.exists
  - name: waiting for server to come back
    # Note that the port parameter is required because of https://github.com/ansible/ansible/issues/9983
    local_action: wait_for host={{ inventory_hostname }} state=started port=22
    sudo: false
    when: not check_rootfs_expanded.stat.exists

- hosts: all
  remote_user: pi
  sudo: yes
  tasks:
  - name: Add Erlang Solutions packaging key
    apt_key: url=https://packages.erlang-solutions.com/debian/erlang_solutions.asc state=present
  - name: Add Erlang Solutions repository
    apt_repository: repo='deb http://packages.erlang-solutions.com/debian jessie contrib' state=present
  - name: Install Erlang Solutions Elixir package
    apt: name=elixir state=latest
  - name: Install Development Erlang Headers
    apt: name=erlang-dev state=latest
  - name: Install Erlang parse tools (needed for yecc module, which is needed by mimetype_parser)
    apt: name=erlang-parsetools state=latest
  - name: Install cmake
    apt: name=cmake state=latest

- hosts: all
  remote_user: pi
  sudo: yes
  tasks:
  - group: name=gpio
  - user: name=gatekeeper home=/var/www groups=gpio,dialout

- hosts: all
  remote_user: pi
  sudo: yes
  roles:
    - nodesource.node
    - jacoelho.phoenix-app
  vars:
    phoenix_app_name: gatekeeper
    phoenix_app_user: gatekeeper
    phoenix_app_group: gatekeeper
    phoenix_app_path: /var/www
    phoenix_app_port: 4000
    phoenix_app_mix_env: prod
    phoenix_app_repository: "https://github.com/alkaloid/gatekeeper.git"
    phoenix_app_version: master
    phoenix_app_run_brunch: true
    phoenix_app_run_migrate: false
    phoenix_app_env: {}
    phoenix_app_configs: []
